In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams["figure.figsize"] = (12,6)

# NumPy

**Задача 1**\
Сгенерировать массив из случайных положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [2]:
import random
np.random.seed(123)
arr = np.random.rand(10)
new_arr = []
for i in range(len(arr)):
    if arr[i-1] > arr.mean():
        new_arr.append(float(arr[i-1]))
print('Сгенерированный массив:', arr,'\nСреднее арифмеическое:', arr.mean(),'\nЭлементы, которые больше среднего арифметического:',new_arr)

Сгенерированный массив: [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752] 
Среднее арифмеическое: 0.544199352975335 
Элементы, которые больше среднего арифметического: [0.6964691855978616, 0.5513147690828912, 0.7194689697855631, 0.9807641983846155, 0.6848297385848633]


**Задача 2**\
Сгенерировать массив из 20 случайных элементов, элементы которого лежат в интервале [0, 10].
+ Определить количество элементов, отличающихся от минимального на 5.
+ Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [3]:
# 1.1
np.random.seed(23)
arr_task2_size = 20
arr_task2 = [np.random.randint(0, 11) for _ in range(arr_task2_size)]
arr_task2

[3, 6, 8, 9, 6, 8, 7, 10, 9, 3, 6, 1, 2, 5, 5, 0, 5, 0, 9, 10]

In [4]:
# 1.2
diff_num_counter = 0
for _ in range(len(arr_task2)):
    if arr_task2[_] == np.min(arr_task2) + 5:
        diff_num_counter += 1
print('В сгенерированном массиве', diff_num_counter, 'элементов, отличающихся от минимального на 5.')

В сгенерированном массиве 3 элементов, отличающихся от минимального на 5.


In [5]:
# 1.3
arr_task2_odds = []
for i in range(len(arr_task2[0::2])):
    if arr_task2[0::2][i] % 2 == 0:
        arr_task2_odds.append(arr_task2[0::2][i])

print('Среднее арифметическое всех четных элементов массива, стоящих на нечетных местах:', float(np.mean(arr_task2_odds)))

Среднее арифметическое всех четных элементов массива, стоящих на нечетных местах: 5.5


**Задача 3**\
Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
+ Возвести в квадрат максимальный элемент матрицы.
+ Все четные числа заменить на 0.

In [6]:
# 1.1
arr_task3_size = 25
arr_task3 = [np.random.randint(0, 11) for _ in range(arr_task3_size)]
arr_task3_matrix = np.array(arr_task3).reshape(5, 5)
arr_task3_matrix

array([[ 9,  3,  1,  7,  4],
       [ 1,  1,  4,  6,  7],
       [ 3, 10,  6,  9,  2],
       [10,  3,  0,  8,  6],
       [ 6,  0,  5,  6,  0]])

In [7]:
# 1.2
max_x = max(arr_task3_matrix, key=max)
max_arr = float(np.max(max_x))
arr_task3_matrix[np.where(arr_task3_matrix == max_arr)] = arr_task3_matrix[np.where(arr_task3_matrix == max_arr)] **2
arr_task3_matrix

array([[  9,   3,   1,   7,   4],
       [  1,   1,   4,   6,   7],
       [  3, 100,   6,   9,   2],
       [100,   3,   0,   8,   6],
       [  6,   0,   5,   6,   0]])

In [8]:
# 1.3
i, j = 0, 0
for i in range(5):
    for j in range(5):
        if arr_task3_matrix[j][i] % 2 == 0:
            arr_task3_matrix[j][i] = 0
arr_task3_matrix

array([[9, 3, 1, 7, 0],
       [1, 1, 0, 0, 7],
       [3, 0, 0, 9, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0]])

**Задача 4**\
Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся.

In [9]:
# 1.1
arr_task4_size = 25
arr_task4 = [np.random.randint(-5, 6) for _ in range(arr_task4_size)]
arr_task4_matrix = np.array(arr_task4).reshape(5, 5)
arr_task4_matrix

array([[-3, -5, -2, -5,  1],
       [-3, -3,  0,  2,  4],
       [-1,  5,  2,  2,  5],
       [-2,  0,  0,  1, -1],
       [ 1,  3,  0, -5, -1]])

In [10]:
# 1.2
negative = (arr_task4_matrix < 0).sum(axis=1)
for i in range(5):
    arr_task4_matrix[i, arr_task4_matrix[i] < 0] = negative[i] 
arr_task4_matrix

array([[4, 4, 4, 4, 1],
       [2, 2, 0, 2, 4],
       [1, 5, 2, 2, 5],
       [2, 0, 0, 1, 2],
       [1, 3, 0, 2, 2]])

# Pandas

In [11]:
df = pd.read_csv("https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv")

In [12]:
df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

**Задание 1**
+ Какой была максимальная цена билета? Медиана?
+ Какова доля выживших?
+ Сколько мужчин / женщин находилось на борту?

In [13]:
# 1
print('Максимальная цена билета:', round(df['fare'].max(), 2), '\nМедиана:', round(df['fare'].median(),2))

Максимальная цена билета: 512.33 
Медиана: 14.45


In [14]:
# 2
print('Доля выживших:', round(len(df[df['survived'] == 1]) / len(df),2))

Доля выживших: 0.38


In [15]:
# 3
print(len(df[df['sex']=='male']), 'мужчин и', len(df[df['sex']=='female']), 'женщин находилось на борту')

843 мужчин и 466 женщин находилось на борту


**Задание 2**
+ Выведите распределение переменной __pclass__ для мужчин и женщин.
    + Сколько мужчин было в первом классе?
    + Сколько женщин было в третьем классе?
      
+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [16]:
# 1.1
pclass_sex = df.pivot_table(index='pclass', columns='sex', values='name', aggfunc='count')
pclass_sex # распределение pclass для мужчин и женщин

sex     female  male
pclass              
1          144   179
2          106   171
3          216   493

In [17]:
# 1.2
print(len(df[(df['sex']=='male') & (df['pclass']==1)]), 'мужчин было в первом классе','\n',len(df[(df['sex']=='female') & (df['pclass']==3)]), 'женщин было в третьем классе')

179 мужчин было в первом классе 
 216 женщин было в третьем классе


In [18]:
# 2
def different_age(x):
    if x < 30:
        return 1 # моложе 30 лет
    elif x >= 60:
        return 3 # старше 60 лет
    else:
        return 2 # от 30 до 60 лет
df['age_group'] = df['age'].apply(different_age)

df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  age_group  
0                     St Louis, MO          1  
1  Montreal, PQ / Chesterville, ON          1  
2  Montreal, PQ / Chesterville, ON          1  
3  Montreal, PQ / Chesterville, ON          2  
4  Montreal, PQ / Chesterville, ON          1

**Задание 3**\
Найдите самое популярное имя среди пассажиров:
+ мужчин;
+ женщин.

In [19]:
# найдем по моде
df['only_name'] = df['name'].str.split(',', n=1).str[0]
print('Самое популярное имя среди пассажиров-мужчин:', df[df['sex'] == 'male']['only_name'].mode()[0], '\nСамое популярное имя среди пассажиров-женщин:', df[df['sex'] == 'female']['only_name'].mode()[0])

Самое популярное имя среди пассажиров-мужчин: Asplund 
Самое популярное имя среди пассажиров-женщин: Andersson


**Задание 4**
+ Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
+ Выведите данные о всех женщинах младше 20 и старше 50 лет.
+ Сколько пассажиров старше 70 лет было на борту?

In [20]:
# 1
df[(df['embarked']=='C') & (df['age']>50)]

pclass  survived                                               name  \
9         1         0                            Artagaveytia, Mr. Ramon   
43        1         1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
48        1         1   Candee, Mrs. Edward (Helen Churchill Hungerford)   
50        1         1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
78        1         1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
104       1         1                     Eustis, Miss. Elizabeth Mussey   
123       1         1                   Frolicher-Stehli, Mr. Maxmillian   
135       1         0                          Goldschmidt, Mr. George B   
136       1         1                          Gracie, Col. Archibald IV   
174       1         0                            Kent, Mr. Edward Austin   
186       1         1          Lindstrom, Mrs. Carl Johan (Sigrid Posse)   
192       1         1                               Lurette, Miss. Elise   
215       1         0                         Newell, Mr. Arthur Webster   
221       1         0                     Ostby, Mr. Engelhart Cornelius   
233       1         1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
246       1         0                             Rothschild, Mr. Martin   
247       1         1     Rothschild, Mrs. Martin (Elizabeth L. Barrett)   
252       1         0                         Ryerson, Mr. Arthur Larned   
264       1         1                Simonius-Blumer, Col. Oberst Alfons   
267       1         0                            Smith, Mr. James Clinch   
276       1         0                      Spencer, Mr. William Augustus   
280       1         1                    Stengel, Mr. Charles Emil Henry   
282       1         1    Stephenson, Mrs. Walter Bertram (Martha Eustis)   
303       1         0                           Warren, Mr. Frank Manley   
304       1         1   Warren, Mrs. Frank Manley (Anna Sophia Atkinson)   
308       1         1              White, Mrs. John Stuart (Ella Holmes)   
316       1         0                        Williams, Mr. Charles Duane   

        sex   age  sibsp  parch    ticket      fare            cabin embarked  \
9      male  71.0      0      0  PC 17609   49.5042              NaN        C   
43   female  60.0      0      0     11813   76.2917              D15        C   
48   female  53.0      0      0  PC 17606   27.4458              NaN        C   
50   female  58.0      0      1  PC 17755  512.3292      B51 B53 B55        C   
78   female  64.0      0      2  PC 17756   83.1583              E45        C   
104  female  54.0      1      0     36947   78.2667              D20        C   
123    male  60.0      1      1     13567   79.2000              B41        C   
135    male  71.0      0      0  PC 17754   34.6542               A5        C   
136    male  53.0      0      0    113780   28.5000              C51        C   
174    male  58.0      0      0     11771   29.7000              B37        C   
186  female  55.0      0      0    112377   27.7208              NaN        C   
192  female  58.0      0      0  PC 17569  146.5208              B80        C   
215    male  58.0      0      2     35273  113.2750              D48        C   
221    male  65.0      0      1    113509   61.9792              B30        C   
233  female  56.0      0      1     11767   83.1583              C50        C   
246    male  55.0      1      0  PC 17603   59.4000              NaN        C   
247  female  54.0      1      0  PC 17603   59.4000              NaN        C   
252    male  61.0      1      3  PC 17608  262.3750  B57 B59 B63 B66        C   
264    male  56.0      0      0     13213   35.5000              A26        C   
267    male  56.0      0      0     17764   30.6958               A7        C   
276    male  57.0      1      0  PC 17569  146.5208              B78        C   
280    male  54.0      1      0     11778   55.4417             C116        C   
282  female  

In [21]:
# 2
df[(df['sex']=='female') & ((df['age']<20) | (df['age']>50))]

pclass  survived                                               name  \
2          1         0                       Allison, Miss. Helen Loraine   
6          1         1                  Andrews, Miss. Kornelia Theodosia   
8          1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
27         1         1            Bishop, Mrs. Dickinson H (Helen Walton)   
...      ...       ...                                                ...   
1265       3         0                          Van Impe, Miss. Catharina   
1273       3         0                 Vander Planke, Miss. Augusta Maria   
1279       3         0               Vestrom, Miss. Hulda Amanda Adolfina   
1300       3         1            Yasbeck, Mrs. Antoni (Selini Alexander)   
1304       3         0                               Zabour, Miss. Hileni   

         sex   age  sibsp  parch    ticket      fare    cabin embarked boat  \
2     female   2.0      1      2    113781  151.5500  C22 C26        S  NaN   
6     female  63.0      1      0     13502   77.9583       D7        S   10   
8     female  53.0      2      0     11769   51.4792     C101        S    D   
11    female  18.0      1      0  PC 17757  227.5250  C62 C64        C    4   
27    female  19.0      1      0     11967   91.0792      B49        C    7   
...      ...   ...    ...    ...       ...       ...      ...      ...  ...   
1265  female  10.0      0      2    345773   24.1500      NaN        S  NaN   
1273  female  18.0      2      0    345764   18.0000      NaN        S  NaN   
1279  female  14.0      0      0    350406    7.8542      NaN        S  NaN   
1300  female  15.0      1      0      2659   14.4542      NaN        C  NaN   
1304  female  14.5      1      0      2665   14.4542      NaN        C  NaN   

       body                        home.dest  age_group      only_name  
2       NaN  Montreal, PQ / Chesterville, ON          1        Allison  
6       NaN                       Hudson, NY          3        Andrews  
8       NaN              Bayside, Queens, NY          2       Appleton  
11      NaN                     New York, NY          1          Astor  
27      NaN                     Dowagiac, MI          1         Bishop  
...     ...                              ...        ...            ...  
1265    NaN                              NaN          1       Van Impe  
1273    NaN                              NaN          1  Vander Planke  
1279    NaN                              NaN          1        Vestrom  
1300    NaN                              NaN          1        Yasbeck  
1304  328.0                              NaN          1         Zabour  

[135 rows x 16 columns]

In [22]:
# 3
print(len(df[df['age'] > 70]), 'пассажиров старше 70 лет было на борту')

6 пассажиров старше 70 лет было на борту


**Задание 5**
+ Посчитайте средний возраст среди мужчин и среди женщин.
+ Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
+ Найдите максимальную стоимость билета в каждом из ценовых классов.

In [23]:
# 1
print('Средний возраст среди мужчин:',round(df['age'][df['sex']=='male'].mean(),2), '\nСредний возраст среди женщин:', round(df['age'][df['sex']=='female'].mean(),2))

Средний возраст среди мужчин: 30.59 
Средний возраст среди женщин: 28.69


In [24]:
# 2
survived_age = df.pivot_table(index='age_group', aggfunc=lambda x: x.sum() / x.count(), values='survived').reset_index()
survived_age # доли выживших в различных возрастных группах

age_group  survived
0          1  0.409490
1          2  0.364286
2          3  0.300000

In [25]:
# 3
print('Максимальная стоимость билета в первом классе:',round(max(df['fare'][df['pclass']==1]),2), '\nМаксимальная стоимость билета во втором классе:', round(max(df['fare'][df['pclass']==2]),2),
      '\nМаксимальная стоимость билета в третьем классе:',round(max(df['fare'][df['pclass']==3]),2))

Максимальная стоимость билета в первом классе: 512.33 
Максимальная стоимость билета во втором классе: 73.5 
Максимальная стоимость билета в третьем классе: 69.55


**Задание 6**\
Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.

In [26]:
pclass_sex_pivot = df.pivot_table(index='pclass', columns='sex', values='name', aggfunc='count')
pclass_sex_pivot

sex     female  male
pclass              
1          144   179
2          106   171
3          216   493

In [27]:
survived_age_pivot = df.pivot_table(index='age_group', aggfunc=lambda x: x.sum() / x.count(), values='survived').reset_index()
survived_age_pivot 

age_group  survived
0          1  0.409490
1          2  0.364286
2          3  0.300000

In [28]:
pclass_fare_pivot = df.pivot_table(index='pclass',aggfunc='max',values='fare').reset_index()
pclass_fare_pivot

pclass      fare
0       1  512.3292
1       2   73.5000
2       3   69.5500